version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - goconst
    - misspell
    - revive
    - exhaustive
  settings:
    exhaustive:
      default-signifies-exhaustive: false
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true

formatters:
  enable:
    - gofmt

run:
  timeout: 5m
