version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - goconst
    - misspell
    - revive

formatters:
  enable:
    - gofmt

run:
  timeout: 5m
