# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - main: .
    binary: lazyspeed
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

brews:
  - repository:
      owner: jkleinne
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/jkleinne/lazyspeed"
    description: "Terminal-based internet speed test"
    license: "MIT"
    test: |
      assert_match "lazyspeed version", shell_output("#{bin}/lazyspeed version")

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
