name: Sync Homebrew Formula

on:
  push:
    tags:
      - 'v*' # Triggers when a tag like v1.0.0 or v0.1.2_9 is pushed

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Bump Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula
        with:
          tap: jkleinne/homebrew-tools
          formula: lazyspeed
          tag: ${{github.ref}}
          token: ${{ secrets.GH_TOKEN }}