name: Sync Homebrew Formula

on:
  push:
    tags:
      - 'v*' # Triggers when a tag like v1.0.0 or v0.1.2_9 is pushed

jobs:
  sync-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Extract version info
        id: vars
        run: |
          TAG_NAME="${{ github.ref_name }}"
          VERSION=${TAG_NAME#v}
          
          echo "Tag: $TAG_NAME, Version: $VERSION"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Calculate SHA256
        id: sha256
        run: |
          URL="https://github.com/${{ github.repository }}/archive/refs/tags/${{ steps.vars.outputs.tag_name }}.tar.gz"
          echo "Downloading from $URL"
          
          curl -L "$URL" -o lazyspeed.tar.gz
          
          SHA=$(sha256sum lazyspeed.tar.gz | cut -d ' ' -f 1)
          echo "SHA256: $SHA"
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Checkout homebrew-tools repository
        uses: actions/checkout@v4
        with:
          repository: jkleinne/homebrew-tools
          token: ${{ secrets.GH_TOKEN }}
          path: homebrew-tools

      - name: Update lazyspeed.rb formula
        working-directory: homebrew-tools/Formula
        run: |
          FILE="lazyspeed.rb"
          echo "Updating $FILE..."
          
          NEW_URL="url \"https://github.com/${{ github.repository }}/archive/refs/tags/${{ steps.vars.outputs.tag_name }}.tar.gz\""
          NEW_SHA="sha256 \"${{ steps.sha256.outputs.sha }}\""

          sed -i "/^ *url /c\  $NEW_URL" $FILE
          
          sed -i "/^ *sha256 /c\  $NEW_SHA" $FILE
          
          echo "Formula updated:"
          cat $FILE

      - name: Commit and push changes
        working-directory: homebrew-tools
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/lazyspeed.rb
          
          if git diff --staged --quiet; then
            echo "No changes detected in the formula. Skipping commit."
          else
            echo "Committing changes..."
            git commit -m "bot(formula): update lazyspeed to ${{ steps.vars.outputs.version }}"
            git push
          fi